/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CreateGameLinkRequest = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'image' : ExternalBlob,
});
export const GameLinkId = IDL.Nat;
export const GameLink = IDL.Record({
  'id' : GameLinkId,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'submittedAt' : IDL.Int,
  'submittedBy' : IDL.Principal,
  'description' : IDL.Text,
  'updatedAt' : IDL.Int,
  'image' : ExternalBlob,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UpdateGameLinkRequest = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'image' : ExternalBlob,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addGameLink' : IDL.Func([CreateGameLinkRequest], [GameLink], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteGameLink' : IDL.Func([GameLinkId], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGameLink' : IDL.Func([GameLinkId], [IDL.Opt(GameLink)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listGameLinks' : IDL.Func([], [IDL.Vec(GameLink)], ['query']),
  'searchGameLinks' : IDL.Func([IDL.Text], [IDL.Vec(GameLink)], ['query']),
  'updateGameLink' : IDL.Func(
      [GameLinkId, UpdateGameLinkRequest],
      [GameLink],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CreateGameLinkRequest = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'image' : ExternalBlob,
  });
  const GameLinkId = IDL.Nat;
  const GameLink = IDL.Record({
    'id' : GameLinkId,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'submittedAt' : IDL.Int,
    'submittedBy' : IDL.Principal,
    'description' : IDL.Text,
    'updatedAt' : IDL.Int,
    'image' : ExternalBlob,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UpdateGameLinkRequest = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'image' : ExternalBlob,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addGameLink' : IDL.Func([CreateGameLinkRequest], [GameLink], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteGameLink' : IDL.Func([GameLinkId], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGameLink' : IDL.Func([GameLinkId], [IDL.Opt(GameLink)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listGameLinks' : IDL.Func([], [IDL.Vec(GameLink)], ['query']),
    'searchGameLinks' : IDL.Func([IDL.Text], [IDL.Vec(GameLink)], ['query']),
    'updateGameLink' : IDL.Func(
        [GameLinkId, UpdateGameLinkRequest],
        [GameLink],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };