/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateGameLinkRequest {
  'url' : string,
  'title' : string,
  'description' : string,
  'image' : ExternalBlob,
}
export type ExternalBlob = Uint8Array;
export interface GameLink {
  'id' : GameLinkId,
  'url' : string,
  'title' : string,
  'submittedAt' : bigint,
  'submittedBy' : Principal,
  'description' : string,
  'updatedAt' : bigint,
  'image' : ExternalBlob,
}
export type GameLinkId = bigint;
export interface UpdateGameLinkRequest {
  'url' : string,
  'title' : string,
  'description' : string,
  'image' : ExternalBlob,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addGameLink' : ActorMethod<[CreateGameLinkRequest], GameLink>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteGameLink' : ActorMethod<[GameLinkId], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGameLink' : ActorMethod<[GameLinkId], [] | [GameLink]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listGameLinks' : ActorMethod<[], Array<GameLink>>,
  'searchGameLinks' : ActorMethod<[string], Array<GameLink>>,
  'updateGameLink' : ActorMethod<[GameLinkId, UpdateGameLinkRequest], GameLink>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];